# Generated by Django 5.2.8 on 2025-11-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО покупателя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('total_purchases', models.PositiveIntegerField(default=0, verbose_name='Общее количество покупок')),
                ('total_spent', models.PositiveIntegerField(default=0, verbose_name='Общая сумма покупок')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='final_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer', verbose_name='Покупатель'),
        ),
    ]
